# Generated by Django 3.0.6 on 2020-05-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=160)),
                ('last_name', models.CharField(max_length=160)),
                ('fiscal_number', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('internal_name', models.TextField()),
                ('report_internal_name', models.TextField()),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'In Process'), (2, 'Error'), (3, 'Success')], default=0)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('glossary', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Document')),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.File'),
        ),
    ]
